export const BlumStatic = {
  URL: 'https://telegram.blum.codes/',
  BOT_ENTITY: '@BlumCryptoBot',
  DEFAULT_HEADERS: {
    'Scheme': 'https',
    'Accept': 'application/json, text/plain, */*',
    'Accept-encoding': 'gzip, deflate, br, zstd',
    'Accept-language': 'ru-UA,ru-RU;q=0.9,ru;q=0.8,en-US;q=0.7,en;q=0.6,uk;q=0.5',
    'Cache-control': 'no-cache',
    'Origin': 'https://telegram.blum.codes',
    'Pragma': 'no-cache',
    'Priority': 'u=1, i',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'User-Agent': 'Mozilla/5.0 (Linux; Android 13; RMX3630 Build/TP1A.220905.001; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/125.0.6422.165 Mobile Safari/537.36',
    'X-Requested-With': 'org.telegram.messenger',
    'Sec-Ch-Ua': '"Android WebView";v="125", "Chromium";v="125", "Not.A/Brand";v="24"',
    'Sec-Ch-Ua-Mobile': '?1',
    'Sec-Ch-Ua-Platform': '"Android"',
  },
}
